/*   Script generated by
Lilac Soul's NWN Script Generator, v. 1.6

For download info, please visit:
http://www.lilacsoul.revility.com    */

//Put this on action taken in the conversation editor

// Moves oPC to "dst_zarni_cut3", out of the area, and resets thier cutscene mode
// status.
void MovePC(object oPC);

void main()
{
    //Introducing the cast, player and Zarniwoop
    object oPC = GetPCSpeaker();
    object oNPC = OBJECT_SELF;

    //Making sure nobody is doing anything
    AssignCommand(oPC, ClearAllActions());
    AssignCommand(oNPC, ClearAllActions());

    // Set the PC into cutscene mode
    SetCutsceneMode(oPC, TRUE);

    //Take your positions
    AssignCommand(oPC, ActionMoveToObject(GetWaypointByTag("dst_zarni_cut1"), FALSE, 0.0));
    AssignCommand(oPC, SetFacing(GetFacing(GetWaypointByTag("dst_zarni_cut1"))));

    AssignCommand(oNPC, ActionMoveToObject(GetWaypointByTag("dst_zarni_cut2"), FALSE, 0.0));
    AssignCommand(oNPC, SetFacing(GetFacing(GetWaypointByTag("dst_zarni_cut2"))));

    //DebugMessage
    //AssignCommand(oNPC, SpeakString("Adams will sue me for this!"));

    //Jumping to the unknown
    DelayCommand(6.0, MovePC(oPC));
}

// Moves oPC to "dst_zarni_cut3", out of the area, and resets thier cutscene mode
// status.
void MovePC(object oPC)
{
    // Define some stuff
    object oMoveTo = GetWaypointByTag("dst_zarni_cut3");
    location lTarget = GetLocation(oMoveTo);
    effect eVis = EffectVisualEffect(VFX_IMP_UNSUMMON);

    // Apply the visual
    ApplyEffectAtLocation(DURATION_TYPE_INSTANT, eVis, GetLocation(oPC));

    // move them to the waypoint (and turn off cutscene mode)
    if(GetCommandable(oPC))
    {
        AssignCommand(oPC, JumpToLocation(lTarget));
        DelayCommand(1.0, SetCutsceneMode(oPC, FALSE));
    }
    else
    {
        SetCommandable(TRUE, oPC);
        AssignCommand(oPC, JumpToLocation(lTarget));
        SetCommandable(FALSE, oPC);
        DelayCommand(1.0, SetCutsceneMode(oPC, FALSE));
    }
}
