@echo off

SETLOCAL

echo ------------------------------------------------------------------------
echo - This script resaves 2da files. The purpose is to keep whitespace     -
echo - uniform, thus preventing lines where just whitespace changed being   -
echo - marked as changed in a later CVS commit.                             -
echo -                                                                      -
echo - If the tool you use for 2da editing does not create similar          -
echo - whitespace as prc.jar 2da utility does, please run this before       -
echo - committing.                                                          -
echo -                                                                      -
echo - All the files are assumed to be located under 2das\                  -
echo ------------------------------------------------------------------------

:start

java -Xmx200m -jar tools\prc.jar 2da -r 2das\baseitems.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\classes.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_atk_4.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_aukn_marsh.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_abcham.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_acego.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_adst.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_ahiero.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_alag.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_alien.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_amn.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_aots.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_arch.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_archv.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_arctrk.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_arti.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_baal.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_bbc.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_beguil.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_bereft.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_bfz.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_binder.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_blades.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_blank.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_blarch.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_bldclw.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_blight.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_blmagu.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_bltl.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_bonded.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_bowman.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_brage.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_brawl.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_brimst.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_bsmith.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_cbtmed.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_cereb.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_chldnt.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_cntmp.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_coc.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_crinti.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_crusdr.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_cultst.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_cwsm.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_dalqur.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_deepst.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_dfa.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_diabol.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_diadra.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_dirge.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_disp.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_dnecro.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_doa.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_dradev.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_dradis.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_drgnht.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_drgshm.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_drnkn.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_drowj.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_drslyr.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_duel.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_duskbl.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_dwdef.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_edisc.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_eldkni.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_enlfis.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_eog.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_etbl.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_etheur.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_factum.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_favsol.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_fh.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_fistra.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_fmm.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_fom.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_forsak.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_foz.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_frebzk.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_frostm.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_frtrgr.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_gfkill.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_hath.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_havocm.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_healer.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_heartw.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_hexbl.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_hextor.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_hfwrlk.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_hiero.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_hmage.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_hnshn.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_hosp.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_hotwm.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_hunter.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_iaij.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_incand.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_incarn.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_irnfrg.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_irnmnd.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_jpm.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_juggr.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_justww.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_kchal.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_kngtwv.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_knight.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_kord.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_kotmc.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_kss.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_lasher.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_lgdr.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_lich.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_maestr.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_magek.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_manat.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_marsh.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_meph.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_mharp.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_minstr.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_ml.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_monine.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_mos.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_mstalc.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_mstrsh.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_myst.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_mystic.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_ninjca.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_noble.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_noctm.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_ocu.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_ollam.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_ootbi.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_ooze.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_orcus.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_orcwar.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_parch.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_pdk.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_psion.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_psych.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_psyrog.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_psywar.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_ragem.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_rava.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_rbyknt.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_redav.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_redwiz.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_rpmlr.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_rune.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_runec.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_sacfis.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_sacpur.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_samur.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_sapphr.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_savant.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_sbheir.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_schord.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_scout.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_sdmind.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_sergrd.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_shaman.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_sharss.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_shdbld.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_shdcst.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_shdsmt.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_shou.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_shugen.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_sklcln.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_sleat.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_sncmnd.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_sod.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_sohei.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_sol.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_soulbn.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_soulc.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_soulkn.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_spellf.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_spells.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_spldnc.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_spnmld.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_ssn.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_storml.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_suel.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_swash.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_swdsge.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_swftwg.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_taltia.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_templ.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_tempst.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_tempus.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_tfshad.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_thaykt.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_thrall.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_tnecro.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_tog.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_totem.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_totrag.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_true.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_unseer.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_urang.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_vassal.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_vigil.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_virt.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_warbld.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_warchf.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_warlok.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_warmnd.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_wayfar.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_wilder.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_wildmg.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_witch.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_wrmage.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_wrslng.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_wwoc.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bfeat_wwolf.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_bind_binder.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_abcham.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_aber.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_acego.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_adst.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_alag.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_alien.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_amn.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_anima.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_antipl.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_aots.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_arch.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_archer.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_archv.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_arctrk.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_arti.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_asasin.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_baal.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_baeln.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_barb.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_bard.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_bbc.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_beguil.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_bereft.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_bfz.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_binder.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_blades.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_blarch.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_bldclw.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_blight.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_blkgrd.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_blmagus.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_bltl.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_bonded.2DA
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_bowman.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_brage.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_brawl.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_brimst.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_bsmith.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_cbtmed.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_cereb.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_chaban.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_chldnt.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_cler.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_cntmp.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_coc.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_comm.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_crea.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_crinti.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_crusdr.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_cultst.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_cwsm.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_dalqur.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_deepst.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_dfa.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_diabol.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_diadra.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_dirge.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_disp.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_divcha.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_dnecro.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_doa.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_dradev.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_dradis.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_drag.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_drgnht.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_drgshm.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_drnkn.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_drowj.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_drslyr.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_druid.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_duel.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_duskbl.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_dwdef.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_edisc.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_eldkni.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_enlfis.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_eog.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_etbl.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_etheur.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_factum.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_favsol.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_fh.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_fight.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_fistra.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_fmm.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_fom.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_forsak.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_foz.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_frebzk.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_frostm.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_frtrgr.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_gfkill.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_gian.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_harper.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_hath.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_havocm.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_healer.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_heartw.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_hexbl.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_hextor.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_hfwrlk.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_hiero.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_hmage.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_hnshn.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_hosp.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_hotwm.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_hunter.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_iaij.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_iblade.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_incand.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_incarn.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_inidra.2DA
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_irnfrg.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_irnmnd.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_jpm.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_juggr.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_justww.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_kchal.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_kngtwv.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_knight.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_kord.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_kotmc.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_kss.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_lasher.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_lgdr.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_lich.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_maestr.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_magek.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_manat.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_marsh.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_meph.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_mharp.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_minstr.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_ml.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_monine.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_monk.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_mos.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_mstalc.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_mstrsh.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_myst.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_mystic.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_necrnm.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_nights.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_ninja.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_ninjca.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_noble.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_noctm.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_ocu.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_ollam.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_ootbi.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_ooze.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_orcus.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_orcwar.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_outs.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_pal.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_palema.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_parch.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_pdk.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_pnpsfr.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_psion.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_psych.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_psyrog.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_psywar.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_pyro.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_ragem.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_rang.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_rava.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_rbyknt.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_redav.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_redwiz.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_rog.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_rpmlr.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_rune.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_runec.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_sacfis.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_sacpur.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_samur.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_sapphr.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_savanta.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_savantc.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_savante.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_savantf.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_sbheir.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_schord.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_scion.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_scout.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_sdhinq.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_sdhstk.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_sdmind.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_sergrd.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_shadep.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_shadow.2DA
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_shaman.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_sharss.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_shdbld.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_shdcst.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_shdsmt.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_shou.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_shugen.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_sklcln.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_sleat.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_sncmnd.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_sod.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_sohei.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_sol.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_sorc.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_soulbn.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_soulc.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_soulkn.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_spellf.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_spells.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_spldnc.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_spnmld.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_ssn.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_storml.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_suel.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_swash.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_swdsge.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_swftwg.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_taltia.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_templ.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_tempst.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_tempus.2DA
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_teneb.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_tfshad.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_thaykt.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_thrall.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_tnecro.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_tog.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_totem.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_totrag.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_true.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_umbral.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_unseer.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_urang.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_urprst.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_vassal.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_vigil.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_virt.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_warbld.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_warchf.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_warlok.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_warmnd.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_warpr.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_wayfar.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_wchbrn.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_wilder.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_wildmg.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_witch.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_wiz.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_wm.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_wrmage.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_wrslng.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_wwoc.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_feat_wwolf.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_invkn_dfa.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_invkn_drgshm.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_invkn_warlok.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_inv_dfa.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_inv_drgshm.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_inv_warlok.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_ivcr_dfa.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_ivcr_drgshm.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_ivcr_warlok.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_mlkn_incand.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_mlkn_incarn.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_mlkn_necrnm.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_mlkn_soulbn.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_mlkn_spnmld.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_mlkn_totem.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_mlkn_umbral.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_move_crusdr.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_move_swdsge.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_move_warbld.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_mvcr_crusdr.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_mvcr_swdsge.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_mvcr_warbld.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_mvkn_crusdr.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_mvkn_swdsge.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_mvkn_warbld.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_mykn_shdcst.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_mykn_shdsmt.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_myst_shdcst.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_myst_shdsmt.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_abcham.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_aber.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_acego.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_adst.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_ahiero.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_alag.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_alien.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_amn.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_ani.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_anima.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_antipl.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_aots.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_arch.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_archer.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_archv.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_arctrk.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_arti.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_baal.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_baeln.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_barb.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_bard.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_bbc.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_beast.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_beguil.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_bereft.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_bfz.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_binder.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_blades.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_blarch.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_bldclw.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_blight.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_blmagus.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_bltl.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_bonded.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_bowman.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_brage.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_brawl.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_brimst.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_bsmith.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_cbtmed.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_cereb.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_chaban.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_chldnt.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_cler.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_cntmp.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_coc.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_con.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_crinti.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_crusdr.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_cultst.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_cwsm.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_dalqur.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_deepst.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_dfa.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_diabol.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_diadra.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_dirge.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_disp.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_divsav.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_dnecro.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_doa.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_dradev.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_dradis.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_drag.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_drgnht.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_drgshm.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_drnkn.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_drowj.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_dru.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_dslyr.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_duel.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_duskbl.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_dwdef.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_edisc.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_eldkni.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_ele.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_enlfis.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_eog.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_etbl.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_etheur.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_factum.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_favsol.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_fey.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_fh.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_fight.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_fistra.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_fmm.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_fom.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_forsak.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_foz.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_frebzk.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_frostm.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_frtrgr.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_gfkill.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_giant.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_hath.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_havocm.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_healer.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_heartw.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_hexbl.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_hextor.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_hfwrlk.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_hiero.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_hmage.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_hnshn.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_hosp.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_hotwm.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_hum.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_hunter.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_iaij.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_iblade.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_incand.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_incarn.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_inidra.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_irnfrg.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_irnmnd.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_jpm.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_juggr.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_justww.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_kchal.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_kngtwv.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_knight.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_kord.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_kotmc.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_kss.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_lasher.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_lgdr.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_lich.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_maestr.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_magbst.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_magek.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_manat.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_marsh.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_meph.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_mharp.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_mharpd.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_minstr.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_ml.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_mon.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_monine.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_monk.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_mos.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_mstalc.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_mstrsh.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_myst.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_mystic.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_necrnm.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_nights.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_ninja.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_ninjca.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_noble.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_noctm.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_ocular.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_ollam.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_ootbi.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_ooze.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_orcus.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_orcwar.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_out.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_pal.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_palema.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_parch.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_pdk.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_plant.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_pnpsfr.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_psion.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_psych.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_psyrog.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_psywar.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_pyro.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_ragem.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_rang.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_rava.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_rbyknt.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_redav.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_redwiz.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_rog.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_rpmlr.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_rune.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_runec.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_sacfis.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_sacpur.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_samur.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_sapphr.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_savant.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_sbheir.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_schord.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_scion.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_scout.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_sdhinq.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_sdhstk.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_sdmind.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_sergrd.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_shadep.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_shaman.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_shape.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_sharss.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_shdbld.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_shdcst.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_shdsmt.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_shou.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_shugen.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_sklcln.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_sleat.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_sncmnd.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_sod.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_sohei.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_sol.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_sorc.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_soulbn.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_soulc.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_soulkn.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_spellf.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_spells.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_spldnc.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_spnmld.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_ssn.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_storml.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_suel.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_swash.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_swdsge.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_swftwg.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_taltia.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_templ.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_tempst.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_tempus.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_teneb.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_tfshad.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_thaykt.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_thrall.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_tnecro.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_tog_a.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_tog_d.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_totem.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_totrag.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_true.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_umbral.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_undead.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_unseer.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_urang.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_urprst.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_vassal.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_vermin.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_vigil.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_virt.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_warbld.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_warchf.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_warlok.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_warmnd.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_warpr.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_wayfar.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_wchbrn.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_wilder.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_wildmg.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_witch.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_wiz.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_wm.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_wrmage.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_wrslng.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_wwoc.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_pres_wwolf.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_psbk_foz.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_psbk_psion.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_psbk_psyrog.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_psbk_psywar.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_psbk_warmnd.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_psbk_wilder.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_psicr_foz.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_psicr_psion.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_psicr_psyrog.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_psicr_psywar.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_psicr_warmnd.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_psicr_wilder.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_psipw_foz.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_psipw_psion.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_psipw_psyrog.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_psipw_psywar.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_psipw_warmnd.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_psipw_wilder.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_savthr_lich.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_abcham.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_acego.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_adst.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_ahiero.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_alag.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_alien.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_amn.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_anima.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_antipl.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_aots.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_arch.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_archer.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_archv.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_arctrk.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_arti.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_asasin.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_baal.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_barb.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_bard.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_bbc.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_beguil.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_bereft.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_bfz.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_binder.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_blades.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_blarch.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_bldclw.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_blight.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_blkgrd.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_blmagu.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_bltl.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_bonded.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_bowman.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_brage.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_brawl.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_brimst.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_bsmith.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_cbtmed.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_cereb.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_chaban.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_chldnt.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_cler.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_cntmp.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_coc.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_crea.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_crinti.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_crusdr.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_cultst.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_dalqur.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_deepst.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_dfa.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_diabol.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_diadra.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_dirge.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_disp.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_divcha.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_dnecro.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_doa.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_dradev.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_dradis.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_drgnht.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_drgshm.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_drnkn.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_drowj.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_drslyr.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_dru.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_duel.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_duskbl.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_dwdef.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_edisc.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_eldkni.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_enlfis.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_eog.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_etbl.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_etheur.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_factum.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_favsol.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_fh.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_fight.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_fistra.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_fmm.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_fom.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_forsak.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_foz.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_frebzk.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_frostm.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_frtrgr.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_gfkill.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_hath.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_havocm.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_healer.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_heartw.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_hexbl.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_hextor.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_hfwrlk.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_hiero.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_hmage.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_hnshn.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_hosp.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_hotwm.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_hunter.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_iaij.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_iblade.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_incand.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_incarn.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_inidra.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_irnfrg.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_irnmnd.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_jpm.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_juggr.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_justww.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_kchal.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_kngtwv.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_knight.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_kord.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_kotmc.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_kss.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_lasher.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_lgdr.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_maestr.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_magek.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_manat.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_marsh.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_meph.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_mharp.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_minstr.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_ml.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_monine.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_monk.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_mos.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_mstalc.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_mstrsh.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_myst.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_mystic.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_necrnm.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_nights.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_ninja.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_ninjca.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_noble.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_noctm.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_ocular.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_ollam.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_ootbi.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_ooze.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_orcus.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_orcwar.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_pal.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_palema.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_parch.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_pdk.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_psion.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_psych.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_psyrog.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_psywar.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_pyro.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_ragem.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_rang.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_rava.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_rbyknt.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_redav.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_redwiz.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_rog.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_rpmlr.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_rune.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_runec.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_sacfis.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_sacpur.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_samur.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_sapphr.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_savant.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_sbheir.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_schord.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_scion.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_scout.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_sdhinq.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_sdhstk.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_sdmind.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_sergrd.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_shadep.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_shadow.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_shaman.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_sharss.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_shdbld.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_shdcst.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_shdsmt.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_shiftr.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_shou.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_shugen.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_sklcln.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_sleat.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_sncmnd.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_sod.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_sohei.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_sol.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_sorc.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_soulbn.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_soulc.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_soulkn.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_spellf.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_spells.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_spldnc.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_spnmld.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_ssn.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_storml.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_suel.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_swash.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_swdsge.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_swftwg.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_taltia.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_templ.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_tempst.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_tempus.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_teneb.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_tfshad.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_thaykt.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_thrall.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_tnecro.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_tog.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_totem.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_totrag.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_true.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_umbral.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_unseer.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_urang.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_urprst.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_vassal.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_vigil.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_virt.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_warbld.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_warchf.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_warlok.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_warmnd.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_warpr.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_wayfar.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_wchbrn.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_wilder.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_wildmg.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_witch.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_wiz.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_wm.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_wrmage.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_wrslng.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_wwoc.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_skill_wwolf.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_spcr_antipl.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_spcr_archv.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_spcr_asasin.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_spcr_bard.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_spcr_beguil.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_spcr_blight.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_spcr_blkgrd.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_spcr_cultst.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_spcr_dnecro.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_spcr_duskbl.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_spcr_favsol.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_spcr_harper.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_spcr_healer.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_spcr_hexbl.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_spcr_hunter.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_spcr_justww.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_spcr_kchal.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_spcr_kngtwv.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_spcr_kotmc.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_spcr_myst.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_spcr_ocu.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_spcr_schord.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_spcr_shaman.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_spcr_sharss.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_spcr_sod.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_spcr_sohei.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_spcr_sol.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_spcr_sorc.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_spcr_suel.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_spcr_templ.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_spcr_tfshad.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_spcr_vassal.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_spcr_vigil.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_spcr_witch.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_spcr_wrmage.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_spell_antipl.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_spell_archv.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_spell_asasin.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_spell_bard.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_spell_beguil.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_spell_blight.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_spell_blkgrd.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_spell_cler.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_spell_cultst.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_spell_dnecro.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_spell_duskbl.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_spell_favsol.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_spell_harper.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_spell_healer.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_spell_hexbl.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_spell_hunter.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_spell_justww.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_spell_kchal.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_spell_kngtwv.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_spell_kotmc.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_spell_myst.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_spell_ocu.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_spell_schord.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_spell_shaman.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_spell_sharss.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_spell_sod.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_spell_sohei.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_spell_sol.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_spell_sorc.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_spell_suel.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_spell_templ.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_spell_tfshad.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_spell_vassal.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_spell_vigil.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_spell_witch.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_spell_wrmage.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_spgn_antipl.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_spgn_archv.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_spgn_asasin.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_spgn_bard.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_spgn_beguil.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_spgn_blight.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_spgn_blkgrd.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_spgn_cultst.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_spgn_dnecro.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_spgn_duskbl.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_spgn_favsol.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_spgn_harper.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_spgn_healer.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_spgn_hexbl.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_spgn_hunter.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_spgn_justww.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_spgn_kchal.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_spgn_kngtwv.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_spgn_kotmc.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_spgn_myst.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_spgn_ocu.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_spgn_rang.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_spgn_schord.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_spgn_shaman.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_spgn_sharss.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_spgn_sod.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_spgn_sohei.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_spgn_sol.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_spgn_sorc.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_spgn_suel.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_spgn_templ.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_spgn_tfshad.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_spgn_vassal.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_spgn_vigil.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_spgn_witch.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_spgn_wrmage.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_spkn_asasin.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_spkn_bard.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_spkn_beguil.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_spkn_dnecro.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_spkn_duskbl.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_spkn_favsol.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_spkn_harper.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_spkn_hexbl.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_spkn_justww.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_spkn_kngtwv.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_spkn_myst.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_spkn_schord.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_spkn_sharss.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_spkn_suel.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_spkn_templ.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_spkn_witch.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_spkn_wrmage.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_stat_alien.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_stat_aots.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_stat_baeln.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_stat_brage.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_stat_dradev.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_stat_dradis.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_stat_eog.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_stat_frostm.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_stat_heartw.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_stat_kord.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_stat_lich.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_stat_ooze.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_stat_palema.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_stat_rune.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_stat_warchf.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_true_known.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_true_maxlvl.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\cls_true_utter.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\colours.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\creaturespeed.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\des_crft_scroll.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\des_crft_spells.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\des_matcomp.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\disease.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\dmgxp.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\domains.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\ECL.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\effecticons.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\epicspells.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\epicspellseeds.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\et_spellblast.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\feat.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\fileends.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\hen_companion.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\hen_familiar.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\iprp_aoe.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\iprp_casterlvl.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\iprp_costtable.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\iprp_damagecost.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\iprp_decvalue1.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\iprp_decvalue2.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\iprp_feats.2DA
java -Xmx200m -jar tools\prc.jar 2da -r 2das\iprp_incvalue1.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\iprp_incvalue2.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\iprp_maxpp.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\iprp_metamagic.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\iprp_monstcost.2DA
java -Xmx200m -jar tools\prc.jar 2da -r 2das\iprp_neg5cost.2DA
java -Xmx200m -jar tools\prc.jar 2da -r 2das\iprp_onhitcost.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\iprp_onhitdur.2DA
java -Xmx200m -jar tools\prc.jar 2da -r 2das\iprp_onhitspell.2DA
java -Xmx200m -jar tools\prc.jar 2da -r 2das\iprp_resistcost.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\iprp_soakcost.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\iprp_speed_dec.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\iprp_speed_enh.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\iprp_spellcost.2DA
java -Xmx200m -jar tools\prc.jar 2da -r 2das\iprp_spells.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\iprp_srcost.2DA
java -Xmx200m -jar tools\prc.jar 2da -r 2das\iprp_storedpp.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\iprp_weightcost.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\itempropdef.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\itemprops.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\la_buyoff.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\masterfeats.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\materialcomp.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\phenotype.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\poison.2DA
java -Xmx200m -jar tools\prc.jar 2da -r 2das\poisontypedef.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\polymorph.2DA
java -Xmx200m -jar tools\prc.jar 2da -r 2das\prc_classes.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\prc_domains.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\prc_familiar.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\prc_polymorph.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\prc_rune_craft.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\prc_spells.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\prc_weap_items.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\ruleset.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\shft_packages.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\shft_pk_animal.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\shft_pk_constrct.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\shft_pk_dragon.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\shft_pk_element.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\shft_pk_gen1.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\shft_pk_gen2.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\shft_pk_outsider.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\shft_pk_rogue.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\shft_pk_undead.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\shft_pk_warrior.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\shifter_abilitie.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\shifter_feats.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\shifter_races.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\skills.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\soulmelds.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\spells.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\spellschools.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\spells_level.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\templates.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\traps.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\unarmed_dmg.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\vestigeabil.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\vestiges.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\vfx_persistent.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\visualeffects.2da
java -Xmx200m -jar tools\prc.jar 2da -r 2das\wol_items.2da

:end

ENDLOCAL